# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rails Performance Fieldbook
email: support@scoutapm.com
description: > # this means to ignore newlines until "baseurl:"
  This is our tattered, weather-worn Rails performance fieldbook. From memory bloat to database optimizations, we're filling it with hard-earned lessons scaling apps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: scoutapp
github_username:  scoutapp
github_repo: fieldbook

# Build settings
markdown: kramdown
permalink: none

gems:
  - jekyll-target-blank
